### ISSUE TITLE
Incompatiblity with cca-console

### ISSUE THREAD

**Issue by cboelter** [contao-community-alliance/dependency-container#10]
I'm using the console extension and the dependency container. If I'm starting the command I get the following error:
```
 [RuntimeException]                   
  Unknown TL_MODE encountered "'CLI'"
```
The Problem is the following code:
https://github.com/contao-community-alliance/dependency-container/blob/master/src/DependencyInjection/Container/ContainerInitializer.php#L262-L265

**Comment by cboelter** [comment]
Gibt es hier schon etwas neues? :(

**Comment by dmolineus** [comment]
Dieses Problem tritt auch in SyncCto auf, falls ein Script in initializeSystems einen Benutzer erwartet. 

`Uncaught exception RuntimeException with message Unknown TL_MODE encountered "'CTO_BE'"`

@discordier Können wir hier mal über eine mögliche Lösung diskutieren? Könnte mir vorstellen, dass man eine Map hat, wo der `TL_MODE` auf einen User-Typ gemappt wird.

Bei `CLI` nicht ganz trivial, da hier der User-Context nicht unbedingt bekannt ist.

**Comment by discordier** [comment]
Da faellt mir nun auch keine allgemeine Loesung ein.
Ich tendiere dazu, im CLI den BE Kontext zu implizieren, in Contao 3 ist dies ebenso im automator, siehe [system/bin/automator](https://github.com/contao/core/blob/fb30e6943318c43dd7a427ee5dd285dabf28824a/system/bin/automator#L28).

**Comment by cboelter** [comment]
Ich benutze es aktuell mit dem TL_MODE BE, in der CLI ... funktioniert ohne Probleme.

**Comment by discordier** [comment]
Should be fixed by now
