### ISSUE TITLE
Contao 4 support

### ISSUE THREAD

**Issue by dmolineus** [contao-community-alliance/dependency-container#11]
I'd like to get our cca tools Contao 4 ready in the next months. I would work on it. 

@discordier You've already started the [migration to symfony](https://github.com/contao-community-alliance/dependency-container/compare/feature-migrate-to-symfony). What's the current state? What are open tasks?

**Comment by discordier** [comment]
The migration is in a dead end, it was only an experiment but will not work out this way.

I tried to implement a backwards and future compatible solution, however this is not as easy as one might think.

We have to make some decisions here.

We could discuss this on mumble in the next days.
