### ISSUE TITLE
You have requested a non-existent service "debug.event_dispatcher".

### ISSUE THREAD

**Issue by richardhj** [contao-community-alliance/dependency-container#15]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/contao-community-alliance/dependency-container/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    7.2      |                                  |
| Contao version:                     |   4.6       |                                  |
| Symfony version: |  4.1 | 

## Issue description

Runing the dev mode, I encounter the following error:
```
 You have requested a non-existent service "debug.event_dispatcher".
```

There most prabably have had been a deprecation notice since Symfony/depependency-injection 2.3.
I found a solution to some similar issue here: garak/KnpPaginatorBundle@fd59b58bc789fcac89109748d1a8401a1170df96

Can't we abandon this package for the dc-general?
 
## Steps to reproduce

1. Update the packages to use Symfony 4
2. Run `contao-console cache:clear --env=dev`

or

1. Save a model in the back end in with app_dev.php as endpoint

## Screenshots

<img width="561" alt="screen shot 2018-08-27 at 08 05 03" src="https://user-images.githubusercontent.com/1284725/44643197-efb8f300-a9cf-11e8-9a5a-a4544109414c.png">

**Comment by baumannsven** [comment]
Fixed in https://github.com/contao-community-alliance/dependency-container/issues/15

**Comment by richardhj** [comment]
👍
