### ISSUE TITLE
Service fails with database defined via DSN

### ISSUE THREAD

**Issue by richardhj** [contao-community-alliance/dependency-container#19]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/contao-community-alliance/dependency-container/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |      4.9.2    |                                  |
| Contao version:                     |     7.4.5     |                                  |

## Issue description

```
Uncaught PHP Exception RuntimeException: "Contao Database is not properly configured." at /var/www/xxx/releases/10/vendor/contao-community-alliance/dependency-container/src/ContaoServices/ServiceFactory.php line 90
```

https://github.com/contao-community-alliance/dependency-container/blob/eee186286c224d61972fd59aa67d291fea69fa92/src/ContaoServices/ServiceFactory.php#L90

Thats because I define the database via DSN in the .env.local instead of using the parameters.yml. As a result, the $config does not hold information about the database.

**Comment by richardhj** [comment]
IMHO these two lines can be removed safely.

**Comment by zonky2** [comment]
@richardhj 

> PHP version: | 4.9.2 |  
> Contao version: | 7.4.5

realy?!

**Comment by richardhj** [comment]
I'm an early adopter…

**Comment by baumannsven** [comment]
Yes @richardhj is right here.

@richardhj can you test the hotfix/2.0.4 please?

**Comment by zonky2** [comment]
closed with https://github.com/contao-community-alliance/dependency-container/commit/0712cb3a7da0652985bfa914da3f440407f4a5ec
